In [ ]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import datetime

In [ ]:
df = pd.read_csv('suv_data.csv')

In [ ]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df['Age'].unique()

array([19, 35, 26, 27, 32, 25, 20, 18, 29, 47, 45, 46, 48, 49, 31, 21, 28,
       33, 30, 23, 24, 22, 59, 34, 39, 38, 37, 42, 40, 36, 41, 58, 55, 52,
       60, 56, 53, 50, 51, 57, 44, 43, 54])

In [ ]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

columns = ['EstimatedSalary']

scaled = df[columns]
scaled_data = scaler.fit_transform(scaled)

scaled_data

array([[-1.49004624],
       [-1.46068138],
       [-0.78528968],
       [-0.37418169],
       [ 0.18375059],
       [-0.34481683],
       [ 0.41866944],
       [ 2.35674998],
       [-1.07893824],
       [-0.13926283],
       [ 0.30121002],
       [-0.52100597],
       [ 0.47739916],
       [-1.51941109],
       [ 0.35993973],
       [ 0.30121002],
       [-1.3138571 ],
       [-1.28449224],
       [-1.22576253],
       [-1.19639767],
       [-1.40195167],
       [-0.60910054],
       [-0.84401939],
       [-1.40195167],
       [-1.37258681],
       [-1.46068138],
       [-1.22576253],
       [-1.16703281],
       [-0.78528968],
       [-1.51941109],
       [ 0.12502088],
       [ 1.97500684],
       [-1.5781408 ],
       [-0.75592482],
       [ 0.59485858],
       [-1.25512738],
       [-1.22576253],
       [-0.60910054],
       [ 0.06629116],
       [-1.13766796],
       [-1.54877595],
       [-0.55037082],
       [ 1.123426  ],
       [-1.60750566],
       [ 0.41866944],
       [-1

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
normalized = df[columns]
normalized_data = scaler.fit_transform(normalized)

normalized_data

array([[0.02962963],
       [0.03703704],
       [0.20740741],
       [0.31111111],
       [0.45185185],
       [0.31851852],
       [0.51111111],
       [1.        ],
       [0.13333333],
       [0.37037037],
       [0.48148148],
       [0.27407407],
       [0.52592593],
       [0.02222222],
       [0.4962963 ],
       [0.48148148],
       [0.07407407],
       [0.08148148],
       [0.0962963 ],
       [0.1037037 ],
       [0.05185185],
       [0.25185185],
       [0.19259259],
       [0.05185185],
       [0.05925926],
       [0.03703704],
       [0.0962963 ],
       [0.11111111],
       [0.20740741],
       [0.02222222],
       [0.43703704],
       [0.9037037 ],
       [0.00740741],
       [0.21481481],
       [0.55555556],
       [0.08888889],
       [0.0962963 ],
       [0.25185185],
       [0.42222222],
       [0.11851852],
       [0.01481481],
       [0.26666667],
       [0.68888889],
       [0.        ],
       [0.51111111],
       [0.03703704],
       [0.47407407],
       [0.288

In [ ]:
from sklearn.preprocessing import LabelEncoder

df_copy = df.copy()
label_encoder = LabelEncoder() 
df_copy['Gender']= label_encoder.fit_transform(df_copy['Gender']) 

df_copy['Gender'].unique()

array([1, 0])

In [ ]:
df_copy2 = df.copy()

df_copy2['Age Class'] = pd.cut(df_copy2['Age'],3,labels=['Below Average','Average','Above Average'])
df_copy2.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased      Age Class
0  15624510    Male   19            19000          0  Below Average
1  15810944    Male   35            20000          0        Average
2  15668575  Female   26            43000          0  Below Average
3  15603246  Female   27            57000          0  Below Average
4  15804002    Male   19            76000          0  Below Average
5  15728773    Male   27            58000          0  Below Average
6  15598044  Female   27            84000          0  Below Average
7  15694829  Female   32           150000          1  Below Average
8  15600575    Male   25            33000          0  Below Average
9  15727311  Female   35            65000          0        Average

In [ ]:
average=df_copy2[df_copy2['Age Class']=='Average']
average.head()

User ID  Gender  Age  EstimatedSalary  Purchased Age Class
1   15810944    Male   35            20000          0   Average
9   15727311  Female   35            65000          0   Average
17  15617482    Male   45            26000          1   Average
18  15704583    Male   46            28000          1   Average
20  15649487    Male   45            22000          1   Average